apiVersion: v1
data:
  SERVER_PORT: "9000"
  ENVIRONMENT: "local"
  MONGODB_URI: "mongodb://root:password123@localhost:27017/?tls=false"
  GOTENBERG_URL: "http://localhost:3000"
  JWT_SECRET: "verysecretkey"
  ADMIN_TOKEN: "pxnanhquan"
kind: ConfigMap
metadata:
  name: lab-admin-go
  namespace: {{.Values.namespace}}
