apiVersion: v1
kind: Service
metadata:
  labels:
    app: lab-admin-go
  name: lab-admin-go
  namespace: {{.Values.namespace}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: lab-admin-go
status:
  loadBalancer: {}
